spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skt?useAffectedRows=true&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
